### ISSUE TITLE
Set up multiple runs of CarboCATLite from CLI, iterating through input parameter files

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/Triangle_workflow#2]
I've added an [example of input files](https://github.com/MindTheGap-ERC/Triangle_workflow/tree/main/data/sea-level_curves) to be passed on to matlab. 
In reality there will be 64 of them and thus 64 runs of Matlab.

So the runs would be like this:
```
matlab -nodesktop -nosplash -r "CarboCAT_cli('params/DbPlatform/paramsInputValues.txt', 'params/DbPlatform/paramsProcesses.txt', 'model_run_42', '../../data/sea-level_curves/Auto000_Allo000_Stoch100V1.txt', false); save('model_run_42.mat', 'model_run_42'); exit"
```
assuming that they are run from [the folder where the local CarboCAT lives](https://github.com/MindTheGap-ERC/Triangle_workflow/tree/main/src/CarboCATLite). I decided to include a local copy of CarboCAT in this repo so we can modify it specifically for this project.

Where the part `Auto000_Allo000_Stoch100V1.txt` is replaced by each subsequent file name.
So this could be e.g. listing all files in the folder and iterating through them.

What to do with the output file name? Best would be to take the same name as the input file (e.g. `model_Auto000_Allo000_Stoch100V1`) but I guess even a numeral (1, 2, 3...) would be fine as long as the order of input files, and thus runs, is fixed.

**Comment by EmiliaJarochowska** [comment]
So far we've only figured out that we can simplify it to:
```
matlab -nodesktop -nosplash -r "CarboCAT_cli('params/DbPlatform/paramsInputValues.txt', 'params/DbPlatform/paramsProcesses.txt', 'model_run_42', '../../data/sea-level_curves/Auto000_Allo000_Stoch100V1.txt', false); exit"
```
but that doesn't solve the problem with `Syntax error: ")" unexpected`

I have a suspicion that matlab on linux cannot take functions with parameters from shell, but it definitely works on mac or windows. TBC.

**Comment by qubixes** [comment]
> So far we've only figured out that we can simplify it to:
> 
> ```
> matlab -nodesktop -nosplash -r "CarboCAT_cli('params/DbPlatform/paramsInputValues.txt', 'params/DbPlatform/paramsProcesses.txt', 'model_run_42', '../../data/sea-level_curves/Auto000_Allo000_Stoch100V1.txt', false); exit"
> ```
> 
> but that doesn't solve the problem with `Syntax error: ")" unexpected`
> 
> I have a suspicion that matlab on linux cannot take functions with parameters from shell, but it definitely works on mac or windows. TBC.

@EmiliaJarochowska @NiklasHohmann Thanks for the help. I managed to get SnakeMake working now with the pipe trick. I suppose that might mean it won't work on Windows though. Perhaps an alternative would be to create a *.m file and run that with command line arguments?

Either way, once I verify that the run completes successfully, I will create a PR. It currently hardcodes the irods collection to Christine's test collection, but that we can change of course.
